### ISSUE TITLE
snapshot.py出现这个抱错是什么情况呢

### ISSUE THREAD

**Issue by 15257741312** [pyecharts/snapshot-selenium#3]
selenium.common.exceptions.JavascriptException: Message: javascript error: echarts is not defined

**Comment by shwangdev** [comment]
同问

**Comment by chfw** [comment]
echarts 没有初始化。我猜是没有网络连接，echarts 需要联网调用。

**Comment by seetimee** [comment]
同问,而且是时不时的,就是用几次偶尔报错一次
